export const moodLanternAbi = [
  {
    type: "function",
    name: "userCalms",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "userFocuses",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "userJoys",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "totalCalms",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "totalFocuses",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "totalJoys",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "lightCalm",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "lightFocus",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "lightJoy",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "event",
    name: "CalmLit",
    inputs: [
      { name: "user", type: "address", indexed: true },
      { name: "userCalms", type: "uint256", indexed: false },
      { name: "totalCalms", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "FocusLit",
    inputs: [
      { name: "user", type: "address", indexed: true },
      { name: "userFocuses", type: "uint256", indexed: false },
      { name: "totalFocuses", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "JoyLit",
    inputs: [
      { name: "user", type: "address", indexed: true },
      { name: "userJoys", type: "uint256", indexed: false },
      { name: "totalJoys", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
] as const;
